### ISSUE TITLE
Build is failing

### ISSUE THREAD

**Issue by EHJ-52n** [52North/52north.github.io#4]
```
[...]
....github.io/src/app/app.component.html 45% building modules 294/327 modules 33 active .../repository/repository.component.html 45% building modules 294/328 modules 34 active ...p/categories/categories.template.html 45% building modules 294/329 modules 35 active .../node_modules/rxjs/util/EmptyError.jsModuleNotFoundError: Module not found: Error: Can't resolve '@angular/cdk' in '/home/travis/build/52North/52north.github.io/node_modules/@angular/material/@angular'
    at factoryCallback (/home/travis/build/52North/52north.github.io/node_modules/webpack/lib/Compilation.js:264:39)
    at /home/travis/build/52North/52north.github.io/node_modules/webpack/lib/NormalModuleFactory.js:247:20
    at /home/travis/build/52North/52north.github.io/node_modules/webpack/lib/NormalModuleFactory.js:65:21
    at /home/travis/build/52North/52north.github.io/node_modules/webpack/lib/NormalModuleFactory.js:138:21
    at /home/travis/build/52North/52north.github.io/node_modules/webpack/node_modules/async/dist/async.js:3861:9
    at /home/travis/build/52North/52north.github.io/node_modules/webpack/node_modules/async/dist/async.js:421:16
    at iteratorCallback (/home/travis/build/52North/52north.github.io/node_modules/webpack/node_modules/async/dist/async.js:996:13)
    at /home/travis/build/52North/52north.github.io/node_modules/webpack/node_modules/async/dist/async.js:906:16
    at /home/travis/build/52North/52north.github.io/node_modules/webpack/node_modules/async/dist/async.js:3858:13
    at /home/travis/build/52North/52north.github.io/node_modules/webpack/lib/NormalModuleFactory.js:130:23
    at onError (/home/travis/build/52North/52north.github.io/node_modules/enhanced-resolve/lib/Resolver.js:65:10)
    at loggingCallbackWrapper (/home/travis/build/52North/52north.github.io/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at afterInnerCallback (/home/travis/build/52North/52north.github.io/node_modules/enhanced-resolve/lib/Resolver.js:146:10)
    at loggingCallbackWrapper (/home/travis/build/52North/52north.github.io/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at Resolver.applyPluginsAsyncSeriesBailResult1 (/home/travis/build/52North/52north.github.io/node_modules/tapable/lib/Tapable.js:227:46)
    at innerCallback (/home/travis/build/52North/52north.github.io/node_modules/enhanced-resolve/lib/Resolver.js:133:19)
    at loggingCallbackWrapper (/home/travis/build/52North/52north.github.io/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at /home/travis/build/52North/52north.github.io/node_modules/tapable/lib/Tapable.js:329:15
    at /home/travis/build/52North/52north.github.io/node_modules/enhanced-resolve/lib/UnsafeCachePlugin.js:40:4
    at loggingCallbackWrapper (/home/travis/build/52North/52north.github.io/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at afterInnerCallback (/home/travis/build/52North/52north.github.io/node_modules/enhanced-resolve/lib/Resolver.js:146:10)
    at loggingCallbackWrapper (/home/travis/build/52North/52north.github.io/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at Resolver.applyPluginsAsyncSeriesBailResult1 (/home/travis/build/52North/52north.github.io/node_modules/tapable/lib/Tapable.js:227:46)
    at innerCallback (/home/travis/build/52North/52north.github.io/node_modules/enhanced-resolve/lib/Resolver.js:133:19)
    at loggingCallbackWrapper (/home/travis/build/52North/52north.github.io/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at /home/travis/build/52North/52north.github.io/node_modules/tapable/lib/Tapable.js:329:15
    at innerCallback (/home/travis/build/52North/52north.github.io/node_modules/enhanced-resolve/lib/Resolver.js:131:11)
    at loggingCallbackWrapper (/home/travis/build/52North/52north.github.io/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at /home/travis/build/52North/52north.github.io/node_modules/tapable/lib/Tapable.js:329:15
    at /home/travis/build/52North/52north.github.io/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:44:6
resolve '@angular/cdk' in '/home/travis/build/52North/52north.github.io/node_modules/@angular/material/@angular'
  Parsed request is a module
  using description file: /home/travis/build/52North/52north.github.io/node_modules/@angular/material/package.json (relative path: ./@angular)
    Field 'browser' doesn't contain a valid alias configuration
  after using description file: /home/travis/build/52North/52north.github.io/node_modules/@angular/material/package.json (relative path: ./@angular)
    resolve as module
      looking for modules in /home/travis/build/52North/52north.github.io/src
        using description file: /home/travis/build/52North/52north.github.io/package.json (relative path: ./src)
          Field 'browser' doesn't contain a valid alias configuration
        after using description file: /home/travis/build/52North/52north.github.io/package.json (relative path: ./src)
          using description file: /home/travis/build/52North/52north.github.io/package.json (relative path: ./src/@angular/cdk)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              /home/travis/build/52North/52north.github.io/src/@angular/cdk doesn't exist
            .ts
              Field 'browser' doesn't contain a valid alias configuration
              /home/travis/build/52North/52north.github.io/src/@angular/cdk.ts doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              /home/travis/build/52North/52north.github.io/src/@angular/cdk.js doesn't exist
            .json
              Field 'browser' doesn't contain a valid alias configuration
              /home/travis/build/52North/52north.github.io/src/@angular/cdk.json doesn't exist
            as directory
              /home/travis/build/52North/52north.github.io/src/@angular/cdk doesn't exist
      looking for modules in /home/travis/build/52North/52north.github.io/node_modules
        using description file: /home/travis/build/52North/52north.github.io/package.json (relative path: ./node_modules)
          Field 'browser' doesn't contain a valid alias configuration
        after using description file: /home/travis/build/52North/52north.github.io/package.json (relative path: ./node_modules)
          using description file: /home/travis/build/52North/52north.github.io/package.json (relative path: ./node_modules/@angular/cdk)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              /home/travis/build/52North/52north.github.io/node_modules/@angular/cdk doesn't exist
            .ts
              Field 'browser' doesn't contain a valid alias configuration
              /home/travis/build/52North/52north.github.io/node_modules/@angular/cdk.ts doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              /home/travis/build/52North/52north.github.io/node_modules/@angular/cdk.js doesn't exist
            .json
              Field 'browser' doesn't contain a valid alias configuration
              /home/travis/build/52North/52north.github.io/node_modules/@angular/cdk.json doesn't exist
            as directory
              /home/travis/build/52North/52north.github.io/node_modules/@angular/cdk doesn't exist

npm ERR! Linux 4.8.12-040812-generic
npm ERR! argv "/home/travis/.nvm/versions/node/v5.6.0/bin/node" "/home/travis/.nvm/versions/node/v5.6.0/bin/npm" "run" "build:prod"
npm ERR! node v5.6.0
npm ERR! npm  v3.6.0
npm ERR! code ELIFECYCLE
npm ERR! 52North.github.io@1.0.0 build:prod: `npm run clean:dist && webpack --config config/webpack.prod.js  --progress --profile --bail`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the 52North.github.io@1.0.0 build:prod script 'npm run clean:dist && webpack --config config/webpack.prod.js  --progress --profile --bail'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the 52North.github.io package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run clean:dist && webpack --config config/webpack.prod.js  --progress --profile --bail
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs 52North.github.io
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls 52North.github.io
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/travis/build/52North/52north.github.io/npm-debug.log


The command "npm run build:prod" exited with 1.

Done. Your build exited with 1.
```
Source: https://travis-ci.org/52North/52north.github.io/builds/255202830

**Comment by janschulte** [comment]
It's up again after commit https://github.com/52North/52north.github.io/commit/163f59e621e34fd588ae5c64a2d60e4bba0c2677
